correct envdir path

diff --git a/misc/dup-s3 b/misc/dup-s3
--- a/misc/dup-s3
+++ b/misc/dup-s3
@@ -10,7 +10,7 @@
 which chpst 2>/dev/null || { echo "ERROR: missing 'chpst' binary from 'runit' package:  sudo apt-get install runit"; exit 2; }
 
 for var in PASSPHRASE AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY; do
-  [ -f ~/.config/envdir/$var ] || { echo "ERROR: missing ~/.config/envdir/$var"; exit 3; }
+  [ -f ~/.config/envdir/duplicity/$var ] || { echo "ERROR: missing ~/.config/envdir/duplicity/$var"; exit 3; }
 done
 
 if [ "$1" == "--clean" ]; then
