improve formatting

diff --git a/misc/dup-s3 b/misc/dup-s3
--- a/misc/dup-s3
+++ b/misc/dup-s3
@@ -15,7 +15,7 @@
 
 [ $# -lt 2 ] && { echo -e "usage: ${0##*/} [--clean] <s3_bucket_path> <path_dirs..>\n e.g.: ${0##*/} --clean s3+http://my-bucket-name/my-device-dir ~/.ssh/ ~/bin/"; exit 1; }
 
-which chpst 2>/dev/null || { echo "ERROR: missing 'chpst' binary from 'runit' package:  sudo apt-get install runit"; exit 2; }
+which chpst >/dev/null 2>/dev/null || { echo "ERROR: missing 'chpst' binary from 'runit' package:  sudo apt-get install runit"; exit 2; }
 
 for var in PASSPHRASE AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY; do
   [ -f ~/.config/envdir/duplicity/$var ] || { echo "ERROR: missing ~/.config/envdir/duplicity/$var"; exit 3; }
@@ -34,7 +34,7 @@ shift
 for item in $*; do
   cd "${item}" || continue
   echo "#################################################"
-  echo "syncing ${item} to ${bucket} .."
+  echo "[ syncing ${item} to ${bucket} .. ]"
 #echo \
   chpst \
     -L /tmp/.lock.dup-s3.${PWD//\//_} \
